# Instigation of NumPy :
Numpy was created in 2005 it is a library used in coding for performing the numerical calculations. It stands for numerical python. Usually it is used for work with arrays. It includes a lot of math functions lik Linear algebra, fourier transforms and random number generation this can be applied to arrays.

## Usage Of NumPy  :
Basically NumPy is a library in coding which is used with SciPy and Mat-Plotlib and its is a replacement for MatLab. NumPy major uses are
- Machine Learning
- Data Science
- Image and Signal Processing
- Scientific Computing

## Operations Using NumPy  :
By using NumPy we can have some main operations like ;
- Mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations which ar related with linear algebra. It has built in functions for operations like linear algebra.

## How to install NumPy library?
First we have to open Vs code after that we have to install extension named as Python. Then we have to make a folder and open that in VS code after that we have to make a new file with extension of .ipynb. Then in terminal we have to write this code after that NumPy will be downloaded automatically:



In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## How to check installed version of NumPy?
To check version of NumPy after we install it in our Vs code we have to run a code which is :

In [3]:
import numpy
numpy.__version__

'1.26.1'

## How to make array by using numpy :
For this we have to run a code and put number of arrays in it :

In [9]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

print(a)



[ 0  1  2  3  4  5  6  7  8  9 10 11]


## How to concatenate 2 arrays  :
For this process we have to make 2 arrays first and put a code there ;

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([6, 7, 8, 9])

np.concatenate((a,b))


array([1, 2, 3, 4, 6, 7, 8, 9])

## How to add 2 arrays with plus sign  :


In [15]:
data = np.array([4, 6])
ones = np.ones(2, dtype=int)
data + ones

array([5, 7])

## How to subbtract using minus sign :
As I have given 2 numbers in above code as data now we can do functions by just calling data variable :

In [16]:
data - ones

array([3, 5])

## How to multiply using product sign :



In [17]:
data * ones

array([4, 6])

## How to divide using divide sign :


In [18]:
data / data

array([1., 1.])

## How to get highest number of an array :


In [19]:
data.max()

6

## How to get lowest number of an array :


In [20]:
data.min()

4